version: '3'
services:
  app:
    container_name: docker-stock-watcher
    resart: always
    build: .
    ports:
      - '80:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
