version: '3'
services:
  app:
    container_name: docker-stock-watcher
    restart: always
    build: .
    ports:
      - '80:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - /data/mongo:/data/db
    ports:
      - '27017:27017'
